name = "cloud-notepad"
main = "src/index.js"
compatibility_date = "2022-05-13"


kv_namespaces = [
  { binding = "NOTES", id = "42ffc893974f461e868dca7121fdb076" },
  { binding = "SHARE", id = "44ca2b00467f47e78bcc2f16af480805" }
]
